(function(){function b(b){isActive=b.parentNode.classList.contains("opened");a();isActive||(b.parentNode.classList.add("opened"),isActive=!0)}function a(){for(var b=0;b<btnDropdowns.length;b++)btnDropdowns[b].parentNode.classList.contains("opened")&&btnDropdowns[b].parentNode.classList.remove("opened")}btnDropdowns=document.querySelectorAll(".btn-dropdown");for(var g=0;g<btnDropdowns.length;g++)btnDropdowns[g].addEventListener?btnDropdowns[g].addEventListener("click",function(a){b(this);a.stopPropagation()}):
btnDropdowns[g].attachEvent("onclick",function(a){b(this);a.stopPropagation()});document.addEventListener?document.addEventListener("click",function(b){b.target.classList.contains("btn-dropdown")||a()}):document.attachEvent("click",function(b){b.target.classList.contains("btn-dropdown")||a()})})();
function checkFieldChange(b){b.classList.contains("field__input")&&(0<b.value.length?b.parentNode.classList.contains("field--filled")||b.parentNode.classList.add("field--filled"):b.parentNode.classList.contains("field--filled")&&b.parentNode.classList.remove("field--filled"));b.classList.contains("field__select")&&(0<b.value.length?b.parentNode.classList.contains("field--filled")||b.parentNode.classList.add("field--filled"):b.parentNode.classList.contains("field--filled")&&b.parentNode.classList.remove("field--filled"))}
(function(){for(var b=document.querySelectorAll(".field__input, .field__select, .field__textarea"),a=0;a<b.length;a++){if(b[a].classList.contains("field__input")||b[a].classList.contains("field__select")||b[a].classList.contains("field__textarea"))0<b[a].value.length?b[a].parentNode.classList.add("field--filled"):b[a].parentNode.classList.remove("field--filled");b[a].addEventListener("focus",function(){checkFieldChange(this);this.parentNode.classList.contains("field--focus")||this.parentNode.classList.add("field--focus")},
!1);b[a].addEventListener("active",function(){checkFieldChange(this);this.parentNode.classList.contains("field--active")||this.parentNode.classList.add("field--active")},!1);b[a].addEventListener("blur",function(b){checkFieldChange(this);this.parentNode.classList.contains("field--focus")&&this.parentNode.classList.remove("field--focus");this.parentNode.classList.contains("field--active")&&this.parentNode.classList.remove("field--active")},!1);b[a].addEventListener("change",function(){this.value?this.parentNode.classList.add("field--filled"):
this.parentNode.classList.remove("field--filled")},!1);b[a].addEventListener("keyup",function(){checkFieldChange(this)},!1);b[a].addEventListener("paste",function(){checkFieldChange(this)},!1)}b=document.getElementsByClassName("field");for(a=0;a<b.length;a++)b[a].addEventListener("click",function(){for(var b=this.childNodes,a=0;a<b.length;a++)b[a].className&&(b[a].classList.contains("field__input")||b[a].classList.contains("field__select")||b[a].classList.contains("field__textarea"))&&b[a].focus()},
!1);b=document.getElementsByClassName("field-state--close");for(a=0;a<b.length;a++)b[a].addEventListener("click",function(){var b=this.parentNode;b.parentNode.classList.remove("has-error");for(var b=b.childNodes,a=0;a<b.length;a++)b[a].className&&(b[a].classList.contains("field__input")&&(b[a].value=""),b[a].classList.contains("field__textarea")&&(b[a].value=""),b[a].classList.contains("field__placeholder")&&(b[a].style.display=""))},!1)})();
(function(){document.querySelectorAll(".fieldset--textarea-auto-expand .field").forEach(function(b){function a(){g.style.height="auto";var b=this.scrollHeight;0<b&&(g.style.height=b+"px")}var g=b.querySelector("textarea.field__textarea");g&&(g.setAttribute("rows",1),g.addEventListener("focus",a),g.addEventListener("input",a),g.addEventListener("change",a),g.dispatchEvent(new Event("change")))})})();
(function(){function b(b){b.parentNode.classList.add("editable-data--edit")}for(var a=document.querySelectorAll(".editable-data__title"),g=0;g<a.length;g++)a[g].addEventListener?a[g].addEventListener("click",function(a){b(this);a.stopPropagation()}):a[g].attachEvent("onclick",function(a){b(this);a.stopPropagation()})})();
(function(){function b(b){b.parentNode.classList.contains("opened")?b.parentNode.classList.remove("opened"):b.parentNode.classList.add("opened")}for(var a=document.querySelectorAll(".dropdown-filter-panel__header"),g=0;g<a.length;g++)a[g].addEventListener?a[g].addEventListener("click",function(a){b(this);a.stopPropagation()}):a[g].attachEvent("onclick",function(a){b(this);a.stopPropagation()})})();
(function(){for(var b=document.querySelectorAll(".collapsible__header"),a=0;a<b.length;a++)b[a].addEventListener("click",function(b){this.parentNode.classList.contains("collapsible--opened")?this.parentNode.classList.remove("collapsible--opened"):this.parentNode.classList.add("collapsible--opened");b.stopPropagation()})})();
function DraggableArea(b,a){function g(){var b="item"+(C.length+1);C.push(b);return b}function x(m){var e=[];m.sort(function(b,m){return b.index-m.index});m.forEach(function(m,a){var h=document.createElement("div");h.className="draggable-item";h.innerHTML='<div class="draggable-item__inner">            <div class="draggable-item__body">                <div class="draggable-item__content"></div>                <div class="draggable-item__control">                    <span class="svg-icon-drag">                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="11" viewBox="0 0 24 11" fill-rule="evenodd" stroke-linecap="square" stroke="#99a9b7" focusable="false"><path d="M.4 1.5L23.6 1.5M.4 5.5L23.6 5.5M.4 9.5L23.6 9.5"></path></svg>                    </span>                </div>            </div>            <div class="draggable-item__placeholder">                <div class="draggable-item__placeholder-inner"></div>            </div>        </div>';
var k=m.key||g();h.setAttribute("data-key",k);h.querySelector(".draggable-item__content").innerHTML=m.content||"";b.appendChild(h);e.push(h)});return e}var C=[],t=[],d=[];a=a||{};var y=document.querySelector("."+a.scrollAreaClass)||window;a.render&&0!=a.items.length?(t=x(a.items),b.classList.add(".draggable-area")):t=b.querySelectorAll(".draggable-item");if(!t)return!1;for(var l=0;l<t.length;l++){var f="";t[l].hasAttribute("data-key")?f=t[l].getAttribute("data-key"):(f=g(),t[l].setAttribute("data-key",
f));f={key:f.toString(),prevIndex:l,nextIndex:-1,startIndex:l,initialX:0,initialY:0,element:t[l],controlElement:function(){return this.element.querySelector(".draggable-item__control")},bodyElement:function(){return this.element.querySelector(".draggable-item__body")}};d.push(f);f.controlElement().addEventListener("mousedown",function(b){return function(e){k(e,b)}}(f));f.controlElement().addEventListener("touchstart",function(b){return function(e){k(e,b)}}(f));f.controlElement().addEventListener("mouseover",
function(b){return function(e){w(e,b)}}(f));f.controlElement().addEventListener("mouseout",function(b){return function(e){h(e,b)}}(f))}var D=!1;try{var z=Object.defineProperty({},"passive",{get:function(){D=!0}});document.addEventListener("testPassive",null,z);document.removeEventListener("testPassive",null,z)}catch(q){}var p=function(b,e){return b.bodyElement().getBoundingClientRect().top+b.bodyElement().offsetHeight>=e.element.getBoundingClientRect().top+2*e.element.offsetHeight/3},c=function(b,
e){return b.bodyElement().getBoundingClientRect().top<=e.element.getBoundingClientRect().top+e.element.offsetHeight/3},B=function(b,e,a){var h=d.indexOf(b),k=d.indexOf(e),c=d[h];d[h]=d[k];d[k]=c;e.element.className+=" draggable-item--placing";setTimeout(function(){e.element.className=e.element.className.replace(" draggable-item--placing","")},400);c=b.element.parentNode;b=c.replaceChild(e.element,b.element);a?c.insertBefore(b,"undefined"!=typeof d[k+1]?d[k+1].element:null):c.insertBefore(b,d[h].element)},
r=function(b,e){b.element.className+=" draggable-item--animate";b.bodyElement().style.transform="translate(0px, "+e+"px)";setTimeout(function(){b.element.className=b.element.className.replace(" draggable-item--animate","");b.bodyElement().style.transform="translate(0, 0)"},50)},A=function(a,e,h,k,c,p){B(a,e,h);k=h?e.element.offsetHeight:-e.element.offsetHeight;a.bodyElement().style.transform="translate(0px, "+(c-k)+"px)";a.initialY+=k;r(e,h?a.element.offsetHeight:-a.element.offsetHeight);e=a.key;
h=a.prevIndex;c=d.indexOf(a);v(b,"onUpdate",d,a,e,h,c,p)},u=function(b){b.preventDefault()},v=function(h,e,k,c,n,p,l,g){var d=document.createEvent("HTMLEvents");d.initEvent(e,!1,!0);d.key=n;d.prevIndex=p;d.nextIndex=l;d.origEvt=g;d.item=c.element;var f=[];k.forEach(function(b,a){f.push({key:b.key,content:b.bodyElement().querySelector(".draggable-item__content").innerHTML})});d.items=f;h.dispatchEvent(d);a[e]&&a[e].call(b,d)},w=function(b,a){a.element.classList.contains("draggable-item--hovered")||
(a.element.className+=" draggable-item--hovered")}.bind(f),h=function(b,a){a.element.className=a.element.className.replace(" draggable-item--hovered","")}.bind(f),k=function(a,e){var h=document.documentElement.scrollTop||document.body.scrollTop||window.pageYOffset,k=0,n=0,l=0,g=0,f=0,t=0,C=!1,r=!1,x,J;a.touches&&a.touches[0]?(e.initialX=a.touches[0].clientX,e.initialY=a.touches[0].clientY):(e.initialX=a.clientX,e.initialY=a.clientY);e.prevIndex=d.indexOf(e);e.element.className+=" draggable-item--dragged";
var q=function(a){var h,m=window.innerHeight||document.documentElement.clientHeight;document.body.classList.add("disable-select");a.touches&&a.touches[0]?(a.preventDefault(),a.stopPropagation(),h=a.touches[0].clientY):h=a.clientY;void 0!=h?J=h:h=J;var G=y===window?window.pageYOffset:0;e.edgeTop=e.bodyElement().getBoundingClientRect().top+G;e.edgeBottom=e.bodyElement().getBoundingClientRect().bottom+G;b.edgeTop=b.getBoundingClientRect().top+G;b.edgeBottom=b.getBoundingClientRect().bottom+G;e.edgeBottom>
b.edgeBottom+10?(g=0<f?g:h,f=1):e.edgeTop<b.edgeTop-10?(l=0<f?l:h,f=2):f=0;t=e.bodyElement().getBoundingClientRect().bottom>m-30?1:30>e.bodyElement().getBoundingClientRect().top?2:0;if(0!=t&&0==f)2==t?C||(C=setInterval(function(){k-=2;y.scrollTop-=2},5)):1==t&&(r||(r=setInterval(function(){e.edgeBottom<b.edgeBottom&&(k+=2,y.scrollTop+=2)},5)));else if(0==t||0!=f)clearInterval(r),clearInterval(C),r=C=!1;void 0!==h?(x=1==f&&h>=g?g:2==f&&h<=l?l:h,n=k):n=1==f?0:2==f?0:k;h=x+n-e.initialY;e.bodyElement().style.transform=
"translate(0px, "+h+"px)";m=d.indexOf(e);0<h&&m<d.length-1?(m=d[m+1],p(this,m)&&A(this,m,!0,e.newTranslateXPos,h,a)):0>h&&0<m&&(m=d[m-1],c(e,m)&&A(this,m,!1,e.newTranslateXPos,h,a))}.bind(e),z=function(b){b=document.documentElement.scrollTop||document.body.scrollTop||window.pageYOffset;b!=h&&(k=b-h)}.bind(e),H=function(a){e.element.className=e.element.className.replace(" draggable-item--dragged","");e.element.className=e.element.className.replace(" draggable-item--hovered","");e.element.classList.remove("draggable-item--hovered");
document.removeEventListener("mousemove",q);document.removeEventListener("mouseup",H);document.removeEventListener("touchmove",q);document.removeEventListener("touchend",H);document.removeEventListener("scroll",z);document.removeEventListener("scroll",q);document.removeEventListener("touchstart",u);e.bodyElement().style.transform="translate(0, 0)";clearInterval(r);clearInterval(C);C=r=!1;var h=e.key,k=e.prevIndex,c=d.indexOf(e);k!==c&&v(b,"onChange",d,e,h,k,c,a);document.body.classList.remove("disable-select")}.bind(e);
document.addEventListener("mousemove",q);document.addEventListener("mouseup",H);document.addEventListener("touchmove",q,D?{passive:!1}:!1);document.addEventListener("touchend",H);document.addEventListener("scroll",z);document.addEventListener("scroll",q);document.addEventListener("touchstart",u,D?{passive:!1}:!1)};this.getState=function(){var b=[];d.forEach(function(a,h){b.push({key:a.key,content:a.bodyElement().querySelector(".draggable-item__content").innerHTML})});return b}}
function initGallery(b){function a(a){function k(a){z(a);var h=0,k=0;a.touches&&a.touches[0]?(h=a.touches[0].clientX,k=a.touches[0].clientY):(h=a.clientX,k=a.clientY);q=k-n.initialY;u=h-n.initialX;c.style.transform="translate("+u+"px, "+q+"px)";c.style.visibility="hidden";overlaped=document.elementFromPoint(h,k);overlapedItem=(overlapedItemId=(overlapedElement=f(overlaped,"gallery__item"))?overlapedElement.getAttribute("data-id"):!1)?d(overlapedItemId):null;c.style.visibility="";n&&overlapedItem&&
n.id!==overlapedItem.id&&(a=overlapedElement.getBoundingClientRect(),beforeElement="left"===(.5<(h-a.left)/((a.right-a.left)/2)?"right":"left")&&overlapedItem.element.nextSibling||overlapedItem.last?overlapedItem.element.nextSibling:overlapedItem.element,oldRect=n.element.getBoundingClientRect(),b.querySelector(".gallery__items-inner").insertBefore(n.element,beforeElement),newRect=n.element.getBoundingClientRect(),y(n.element,oldRect,newRect),x())}function m(b){z(b);document.removeEventListener("mousemove",
k);document.removeEventListener("mouseup",m);c&&(ghostNewX=p.offsetLeft-e.scrollLeft,ghostNewY=p.offsetTop,ghostShiftX=t-ghostNewX,ghostShiftY=A-ghostNewY,c.style.left=p.offsetLeft-e.scrollLeft+"px",c.style.top=p.offsetTop+"px",newnewX=u+ghostShiftX,newnewY=q+ghostShiftY,c.style.transform="translate("+newnewX+"px, "+newnewY+"px)",forRepaintDummy=c.offsetWidth,c.style.transition="all 200ms",c.style.transform="translate(0px, 0px)",setTimeout(function(){l(n.element,"gallery__item--hovered",!0);setTimeout(function(){l(n.element,
"gallery__item--hovered",!1)},210);l(n.element,"gallery__item--dragged",!1);n.element.querySelector(".gallery__item-inner").style.transform="translate(0, 0)";C();setTimeout(function(){c.parentElement.removeChild(c)},200)},200))}x();if(r)return!1;var e=f(a.target,"gallery__items-inner"),p=f(a.target,"gallery__item"),g=p?p.getAttribute("data-id"):"",n=d(g);a.touches&&a.touches[0]?(n.initialX=a.touches[0].clientX,n.initialY=a.touches[0].clientY):(n.initialX=a.clientX,n.initialY=a.clientY);c&&c.parentElement&&
c.parentElement.removeChild(c);c=n.element.cloneNode(!0);c.style.width=n.element.offsetWidth+"px";c.style.height=n.element.offsetHeight+"px";c.querySelector(".gallery__item-inner").style.width=n.element.offsetWidth+"px";c.querySelector(".gallery__item-inner").style.height=n.element.offsetHeight+"px";document.addEventListener("mousemove",k);document.addEventListener("mouseup",m);c.classList.add("gallery__item--ghost");c.style.left=n.element.offsetLeft-e.scrollLeft+"px";c.style.top=n.element.offsetTop+
"px";var t=n.element.offsetLeft-e.scrollLeft,A=n.element.offsetTop,q=0,u=0;b.querySelector(".gallery__items").appendChild(c);l(n.element,"gallery__item--dragged",!0);l(c,"gallery__item--ghost-dragged",!0)}function g(a){function k(){n=!0;A&&clearTimeout(A)}function m(){E.selected?p(E):n||e(E);n=!1;A&&clearTimeout(A);E.element.removeEventListener("touchmove",k);E.element.removeEventListener("touchend",m)}function e(b){b.selected=!0;l(b.element,"gallery__item--hovered",!0);l(b.element,"gallery__item--selected",
!0);clearInterval(B);clearInterval(v);v=B=!1;g(b)}function p(b){b.selected=!1;l(b.element,"gallery__item--hovered",!1);l(b.element,"gallery__item--selected",!1);l(b.element,"gallery__item--dragged",!1);c&&(c.parentElement.removeChild(c),c=null)}function g(a){function h(k){n=!0;z(k);k.touches&&k.touches[0]?(clientX=k.touches[0].clientX,clientY=k.touches[0].clientY):(clientX=k.clientX,clientY=k.clientY);0>c.getBoundingClientRect().left&&0<w.scrollLeft?B||(B=setInterval(function(){w.scrollLeft-=2},5)):
c.getBoundingClientRect().right>t?v||(v=setInterval(function(){w.scrollLeft+=2},5)):(clearInterval(B),clearInterval(v),v=B=!1);newTranslateXPos=clientX-a.initialX;newTranslateYPos=clientY-a.initialY;c.style.transform="translate("+Math.ceil(newTranslateXPos)+"px, "+Math.ceil(newTranslateYPos)+"px)";k=null;c.style.visibility="hidden";overlaped=document.elementFromPoint(clientX,clientY);k=(overlapedItemId=(overlapedElement=f(overlaped,"gallery__item"))?overlapedElement.getAttribute("data-id"):!1)?d(overlapedItemId):
null;c.style.visibility="";if(a&&k&&a.id!==k.id){var e=overlapedElement.getBoundingClientRect();beforeElement="left"===(.5<(clientX-e.left)/((e.right-e.left)/2)?"right":"left")&&k.element.nextSibling||k.last?k.element.nextSibling:k.element;oldRect=a.element.getBoundingClientRect();b.querySelector(".gallery__items-inner").insertBefore(a.element,beforeElement);newRect=a.element.getBoundingClientRect();y(a.element,oldRect,newRect);x()}}function r(b){z(b);if(!n)return p(a),!1;clearInterval(B);clearInterval(v);
v=B=!1;document.removeEventListener("touchmove",h);document.removeEventListener("touchend",r);ghostNewX=F.offsetLeft-w.scrollLeft;ghostNewY=F.offsetTop;ghostShiftX=a.ghostInitX-ghostNewX;ghostShiftY=a.ghostInitY-ghostNewY;c.style.left=F.offsetLeft-w.scrollLeft-2+"px";c.style.top=F.offsetTop-2+"px";newnewX=newTranslateXPos+ghostShiftX;newnewY=newTranslateYPos+ghostShiftY;c.style.transform="translate("+newnewX+"px, "+newnewY+"px)";forRepaintDummy=c.offsetWidth;c.style.transition="all 200ms";c.style.transform=
"translate(0px, 0px)";l(a.element,"gallery__item--dragged",!1);setTimeout(function(){a.element.removeEventListener("touchmove",k);a.element.removeEventListener("touchend",m);C();a.selected?p(a):n||e(a);n=!1},200)}if(c)return!1;c=a.element.cloneNode(!0);c.classList.add("gallery__item--ghost");l(a.element,"gallery__item--dragged",!0);a.ghostInitX=a.element.offsetLeft-w.scrollLeft;a.ghostInitY=a.element.offsetTop;c.style.width=a.element.offsetWidth+"px";c.style.height=a.element.offsetHeight+"px";c.style.left=
a.element.offsetLeft-w.scrollLeft+"px";c.style.top=a.element.offsetTop+"px";b.querySelector(".gallery__items").appendChild(c);c.style.transition="width 200ms, height 200ms, left 200ms, top 200ms, box-shadow 200ms";c.style.width=a.element.offsetWidth+4+"px";c.style.height=a.element.offsetHeight+4+"px";c.style.left=a.element.offsetLeft-w.scrollLeft-2+"px";c.style.top=a.element.offsetTop-2+"px";setTimeout(function(){c.style.transition=""},200);c.addEventListener("touchstart",function(b){b.touches&&b.touches[0]?
(a.initialX=b.touches[0].clientX,a.initialY=b.touches[0].clientY):(a.initialX=b.clientX,a.initialY=b.clientY)},u?{passive:!1}:!1);c.addEventListener("touchmove",h,u?{passive:!1}:!1);c.addEventListener("touchend",r,u?{passive:!1}:!1)}r=!0;var n=!1,t=window.innerWidth||document.documentElement.clientWidth,B=!1,v=!1,w=f(a.target,"gallery__items-inner"),F=f(a.target,"gallery__item"),I=F?F.getAttribute("data-id"):"",E=d(I);E.initialX=0;E.initialY=0;q.forEach(function(a,b){a.id!==I&&p(a)});E.element.addEventListener("touchmove",
k,u?{passive:!1}:!1);E.element.addEventListener("touchend",m,u?{passive:!1}:!1);document.addEventListener("touchstart",function(a){D(a.target,"gallery__item")||q.forEach(function(a,b){p(a)})},u?{passive:!1}:!1);x();A=setTimeout(function(){m()},400)}function x(){for(var a=document.querySelectorAll(".gallery__item--draggable:not(.gallery__item--hidden)"),b=0;b<a.length;b++){var c=a[b].getAttribute("data-id");if(!c)break;c=d(c);c.first=0===b;c.last=b===a.length-1}}function C(){q.forEach(function(a,b){a.main=
a.first});t()}function t(){q.forEach(function(a,b){l(a.element,"gallery__item--marked",a.main)})}function d(a){var b={};q.forEach(function(c,e){c.id===a&&(b=c)});return b}function y(a,b,c){a.style.transform="translate("+-(c.left-b.left)+"px, "+-(c.top-b.top)+"px)";a.style.transition="transform 200ms";a.style.transform="translate(0px, 0px)";setTimeout(function(){a.style.transition="";a.style.transform=""},200)}function l(a,b,c){c?a.classList.contains(b)||a.classList.add(b):a.classList.remove(b)}function f(a,
b){do{if(a&&a.classList&&a.classList.contains(b))return a;a=a.parentNode}while(a);return!1}function D(a,b){do if((a=a.parentNode)&&a.classList&&a.classList.contains(b))return!0;while(a);return!1}function z(a){a.preventDefault();a.stopPropagation()}if(!b)return!1;var q=[],p=[],c,B=!1,r=!1,A=!1,u=!1;try{var v=Object.defineProperty({},"passive",{get:function(){u=!0}});window.addEventListener("testPassive",null,v);window.removeEventListener("testPassive",null,v)}catch(w){}window.addEventListener("resize",
function(){clearTimeout(B);B=setTimeout(function(){var a=window.innerWidth||document.documentElement.clientWidth,c=b.querySelector(".gallery.gallery--hide-items .gallery__items-inner");if(c){var m=c.offsetWidth,c=c.children,e=0;if(1024>a)for(a=0;a<c.length;a++)l(c[a],"gallery__item--hidden",!1);else for(a=0;a<c.length;a++)l(c[a],"gallery__item--hidden",!1),e=e+c[a].offsetWidth+8,e-8>m&&l(c[a],"gallery__item--hidden",!0)}if(a=b.querySelector(".gallery:not(.gallery--hide-items) .gallery__items-inner")){for(var m=
a.children,e=a.offsetWidth,p=0,f=0,a=a.children.length,c=!1,g=window.innerWidth||document.documentElement.clientWidth,d=0;d<m.length;d++)l(m[d],"gallery__item--hidden",!1);if(1024>g)for(d=0;d<m.length;d++)m[d].style.width="125px";else{for(d=0;d<m.length;d++)g=d+1,p=p+100+8,f=f+150+8,p<e&&f>e&&(c=g);if(c)for(e=Math.ceil(a/c),p=a%c,numberInRow=2>p&&0!==p?2<e?c-1:a-2:c,d=0;d<m.length;d++)m[d].style.width="calc( 100% / "+numberInRow+" - 8px)",1===Math.ceil(a/numberInRow)?m[d].style.maxWidth="125px":m[d].style.maxWidth=
"";else for(d=0;d<m.length;d++)m[d].style.width="125px"}}},250)});(function(){for(var c=b.querySelectorAll(".gallery__item--draggable:not(.gallery__item--hidden)"),k={},d=0;d<c.length;d++)k="image"+(p.length+1),p.push(k),k={id:k,selected:!1,main:0===q.length,element:c[d],first:0===d,last:d===c.length-1},c[d].setAttribute("data-id",k.id),c[d].addEventListener("mousedown",a),c[d].addEventListener("touchstart",g),q.push(k)})();t()}
(function(){var b=document.querySelectorAll("[type=range]");if(b)for(var a=b.length-1;0<=a;a--){var g=function(a){var b=a.parentNode.querySelector(".range__tooltip");if(b){var g=a.getAttribute("data-unit"),d=a.parentNode,y=d.querySelector(".range__limit--start").offsetWidth,l=d.querySelector(".range__limit--end").offsetWidth,f=a.getAttribute("max"),f=a.value/f*(d.offsetWidth-20);d.classList.toggle("range--limit-start",f>y);d.classList.toggle("range--limit-end",f<d.offsetWidth-l-24);b.innerHTML=a.value+
g;b.style.left=f+"px"}};b[a].style.setProperty("--min",+b[a].getAttribute("min"));b[a].style.setProperty("--max",+b[a].getAttribute("max"));b[a].parentNode.style.setProperty("--val",+b[a].getAttribute("val"));b[a].value=b[a].getAttribute("val");g(b[a]);b[a].addEventListener("input",function(){this.parentNode.style.setProperty("--val",+this.value);g(this)},!1)}})();
(function(){function b(a){return a.classList.contains("dropdown-list-item__header--checked")}function a(a){return a.classList.contains("dropdown-list-item__header--unchecked")}function g(a){b(a)||(a.classList="dropdown-list-item__header dropdown-list-item__header--checked dropdown-list-item__header--animated",setTimeout(function(){a.classList="dropdown-list-item__header dropdown-list-item__header--checked"},200))}function x(a){return(a=a.getElementsByClassName("dropdown-list-item__subitems")[0])?
a.querySelectorAll(".dropdown-list-item"):[]}function C(a){isActive=a.parentNode.classList.contains("field--opened");isActive||(d(),a.parentNode.classList.add("field--opened"),isActive=!0)}function t(a,b){z&&D&&q&&(""===b?(z.classList.add("hidden"),D.classList.remove("hidden")):(D.classList.add("hidden"),q.innerHTML='<a><b>Create category "'+b+'"</b></a>',z.classList.remove("hidden")));for(var d=0;d<a.length;d++){var g=a[d];if(0<x(g).length){t(x(g),b);var f;a:{f=x(g);for(var l=0;l<f.length;l++)if(!f[l].classList.contains("hidden")){f=
!0;break a}f=!1}f?g.classList.remove("hidden"):g.classList.add("hidden")}else(f=g.querySelectorAll(".dropdown-list-item__header"))&&0<f.length&&(f=f[0],f.classList.contains("dropdown-list-item__header--no-icon")||f.classList.contains("dropdown-list-item__header--add-new")||(f.innerHTML.includes(b)?g.classList.remove("hidden"):g.classList.add("hidden")))}}function d(){for(var a=0;a<f.length;a++){var b=f[a].parentNode;b.classList.contains("field--opened")&&b.classList.remove("field--opened");var d=
b.getElementsByClassName("dropdown-list-item");0<d.length&&(f[a].value="",b.classList.remove("field--filled"),t(d,""))}}var y=document.getElementsByClassName("dropdown-list-item__header");[].forEach.call(y,function(d){d.addEventListener("click",function(){a(d)||d.classList.contains("dropdown-list-item__header--indeterminate")?g(d):b(d)&&(a(d)||(d.classList="dropdown-list-item__header dropdown-list-item__header--unchecked"))})});for(var y=document.querySelectorAll(".fieldset--combo"),l=0;l<y.length;l++)y[l].addEventListener("click",
function(a){var b=this.getElementsByClassName("field__input")[0];C(b);a.stopPropagation()});for(var f=document.querySelectorAll(".fieldset--combo .field__input"),l=0;l<f.length;l++)f[l].addEventListener("click",function(a){C(this);a.stopPropagation()}),f[l].addEventListener("input",function(a){var b=this.parentNode.getElementsByClassName("dropdown-list-item");t(b,this.value);a.stopPropagation()});var D=document.getElementById("note-item"),z=document.getElementById("add-item"),q;z&&(y=z.getElementsByClassName("dropdown-list-item__header"))&&
0<y.length&&(q=y[0]);document.addEventListener("click",function(a){a.target.classList.contains("dropdown-list-item__header")||d()})})();
(function(){var b=[],a=function(a,b){function d(b){b=new CustomEvent("onChange",{bubbles:!0,cancelable:!0,detail:{color:b}});a.dispatchEvent(b)}function g(){var b=a.querySelectorAll(".palette__item--selected");[].forEach.call(b,function(a){a.classList.remove("palette__item--selected")})}function l(c){g();c.classList.add("palette__item--selected");b=c.getAttribute("data-color");var d=a.querySelector(".color-picker__custom");c.classList.contains("color-picker__swatch")||d.classList.add("color-picker__custom--collapsed")}
function f(){return a}function x(){return"rgba("+v.getColor().toRGBA().map(function(a,b){return Number(a.toFixed(3>b?0:2))}).toString()+")"}function z(a,b){function c(a){d.style.color=a;return window.getComputedStyle(d,null).getPropertyValue("color")}var d=document.createElement("span");d.style.display="none";document.body.appendChild(d);var f=c(a)===c(b);d.parentNode.removeChild(d);return f}function q(d,f){void 0===f&&(f=!1);var e=a.querySelector(".color-picker__custom"),h=!1;b=d;setTimeout(function(){v.setColor(d);
if(d){if(c){f||[].forEach.call(c,function(a){z(a.value,d)&&(l(a.el),e.classList.contains("color-picker__custom--collapsed")||e.classList.add("color-picker__custom--collapsed"),h=!0)});if(!h){g();setTimeout(function(){v.setColor(d)},0);var p=a.querySelector(".color-picker__swatch");p&&(p.style.backgroundColor=d);e.classList.remove("color-picker__custom--collapsed")}setTimeout(function(){b=x()},0)}}else g(),e.classList.contains("color-picker__custom--collapsed")||e.classList.add("color-picker__custom--collapsed")},
0)}function p(){return b}a=a||null;b=b||"#FFFFFF";var c=[],B=!0,r;if(a){var A=a.querySelectorAll(".palette__item");if(A)for(var u=0;u<A.length;u++)A[u].style.backgroundColor=A[u].getAttribute("data-color"),A[u].addEventListener("click",function(){l(this);d(this.style.backgroundColor)}),r=A[u].getAttribute("data-color"),c[u]={el:A[u],value:r},r==b&&l(c[u].el);var v=new Pickr({el:a.querySelector(".color-picker__swatch"),parent:a.querySelector(".color-picker__custom"),default:b,position:"right",comparison:!1,
useAsButton:!0,components:{preview:!1,opacity:!0,hue:!0},onChange:function(c,f){if(B){var e=a.querySelector(".field__input"),g=a.querySelector(".color-picker__swatch");c=v.getColor();e.value=c.toHEX().toString();e.dispatchEvent(new Event("change"));b=c.toRGBA().toString();d(b);g.setAttribute("data-color",b);l(g);h.classList.remove("has-error")}}}),w=a.querySelector(".field__input"),h=w.parentNode.parentNode;w.value=b;w.dispatchEvent(new Event("change"));w.addEventListener("input",function(){B=!1;
var b=v.setColor(w.value,!0);w.value?b?(l(a.querySelector(".color-picker__swatch")),h.classList.remove("has-error")):h.classList.contains("has-error")||h.classList.add("has-error"):(v.setColor("#FFFFFF",!0),h.classList.remove("has-error"));d(x());setTimeout(function(){B=!0},0)});w.addEventListener("focus",function(){var c=a.querySelector(".color-picker__swatch");l(c);q(b,!0);v.show()});w.addEventListener("blur",function(){this.value||q(b,!0)});(r=a.querySelector(".color-picker__swatch"))&&r.addEventListener("click",
function(){q(b,!0)});r=document.querySelectorAll(".pcr-app .field__input");r=r[r.length-1];r.addEventListener("input",function(){this.value?this.parentNode.classList.add("field--filled"):this.parentNode.classList.remove("field--filled")});r.addEventListener("focus",function(){this.parentNode.classList.add("field--focus")});r.addEventListener("blur",function(){this.parentNode.classList.remove("field--focus")});(r=a.querySelector(".color-picker__custom--collapsed + .btn"))&&r.addEventListener("click",
function(){a.querySelector(".color-picker__custom--collapsed")&&(b=b||"#FFFFFF",q(b,!0),v.show())});this.getElem=f;this.setColor=q;this.getColor=p}},g=document.querySelectorAll(".color-picker");if(g)for(var x=0;x<g.length;x++)b.push(new a(g[x]));this.pickers=b})();